### ISSUE TITLE
Create API endpoints for User registration

### ISSUE THREAD

**Issue by minndoo** [varwishteam/varwish-be#3]
Acceptance criteria:
* Server will receive a request to register an user. 
* User is permanently stored in database
* User's password is hashed 

```
POST /signup      // Create new User
   requestBody: {
       firstName,
       lastName,
       username,
       age,
       email,
       password        // Hashed password
   }

```

**Comment by tonyskansf** [comment]
User's password is hashed ;) See #4 Create API for user auth

**Comment by tonyskansf** [comment]
Implemented. See #4
