### ISSUE TITLE
Create API for user auth

### ISSUE THREAD

**Issue by minndoo** [varwishteam/varwish-be#4]
User's credential will be checked on request to login, successful login will provide him a _JWToken_
Acceptance criteria:
* User's credentials need to be checked from database
* Send an adequate response (doesn't exist, wrong credentials, success)
* If user logs in, he will be provided a _JWToken_

```
POST /login         // Log user in
   requestBody: {
       email,          // Optional
       username,       // Optional
       password        // Hashed password
   }                   // Either username or email must be filled in

```

**Comment by tonyskansf** [comment]
User authentication created using django-allauth framework - not JWToken (will be implemented later), the goal was to tryout auth and the mongodb => the user signed up will be automatically added to the db. The user is authenticated with username & password.

API Endpoints:
/rest-auth/login/
/rest-auth/registration

**Comment by minndoo** [comment]
Can we make the endpoints just
```
 /login
/registration
```

**Comment by tonyskansf** [comment]
Final endpoints for user authentication
```Javascript
POST /login/
  {
    "username": "",
    "email": "",
    "password": ""
  }

Response:
  {
    "key": "7084b86bc2e064abaf3f08f2cc04e62b1ea4350e", // token
    "user": 9, // user's ID
    "user_type": {
        "id": 9
    }
  }

POST /sign-up/
  {
    "username": "",
    "email": "",
    "password1": "",
    "password2": "",
    "first_name": "",
    "last_name": ""
  }

Response:
{
    "key": "7084b86bc2e064abaf3f08f2cc04e62b1ea4350e", // token
    "user": 9, // users's ID
    "user_type": {
        "id": 9
    }
}
```
